### ISSUE TITLE
1.14.4 warns of not having valid resource pack

### ISSUE THREAD

**Issue by Old-Man-D** [Parker8283/BowInfinityFix#4]
I just added this mod to my custom pack, and it's saying it "failed to load a valid resource pack info".  Otherwise the mod seems to work still.

**Comment by Parker8283** [comment]
Please post your log to [Pastebin](https://pastebin.com/) or [Gist](https://gist.github.com/) and post the link here so I can take a look.

**Comment by Parker8283** [comment]
Never mind, found the issue I believe. Pushing a fix soon.

**Comment by Parker8283** [comment]
Build will be up on CurseForge soon.
